# Travis CI (https://travis-ci.org/)

language: c
dist: bionic
cache:
  apt: true # only works with Pro version

before_install:
  - cd .. && git clone https://github.com/florianschanda/miss_hit.git && export PATH=$PATH:`pwd`/miss_hit && cd CPP_PTB

jobs:
  include:
    - script: mh_style `pwd`
      name: "miss_hit linter" # names the second job